version: '3.8'

services:
  lmslendings_query:
    image: lmslendings:query
    environment:
      - SPRING_PROFILES_ACTIVE=mongodb,bootstrap
      - spring.data.mongodb.uri=mongodb://mongodb_lms:27017/LMS_Lending_Query
      - spring.datasource.url=jdbc:postgresql://postgres_query:5432/query_lendings
      - spring.datasource.username=postgres
      - spring.datasource.password=password
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
      - spring.jpa.hibernate.ddl-auto=update
      - spring.rabbitmq.host=rabbitmq
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 1m
    ports:
      - "8091:8080"
    networks:
      - lms_network
    depends_on:
      - postgres_query
      - rabbitmq

  postgres_query:
    image: postgres:latest
    environment:
      - POSTGRES_DB=query_lendings
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_query_data:/var/lib/postgresql
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 1m
    ports:
      - "5444:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lms_network

networks:
  lms_network:
    external: true

volumes:
  postgres_query_data:
    driver: local