version: '3.8'

services:
  lmslendings_command:
    image: lmslendings:command
    environment:
      - SPRING_PROFILES_ACTIVE=mongodb,bootstrap
      - spring.data.mongodb.uri=mongodb://mongodb_lms:27017/LMS_Lending_Command
      - spring.datasource.url=jdbc:postgresql://postgres_command:5432/command_lendings
      - spring.datasource.username=postgres
      - spring.datasource.password=password
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
      - spring.jpa.hibernate.ddl-auto=update
      - spring.rabbitmq.host=rabbitmq
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 1m
    ports:
      - "8090:8080"
    networks:
      - lms_network

  postgres_command:
    image: postgres:latest
    environment:
      - POSTGRES_DB=command_lendings
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_command_data:/var/lib/postgresql
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 1m
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lms_network

networks:
  lms_network:
    external: true

volumes:
  postgres_command_data:
    driver: local