version: '3.8'

services:
  lmsbooks_query:
    image: lmsbooks:query
    environment:
      - SPRING_PROFILES_ACTIVE=
      - spring.datasource.url=jdbc:postgresql://postgres_query:5432/query_books
      - spring.datasource.username=postgres
      - spring.datasource.password=password
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
      - spring.jpa.hibernate.ddl-auto=update
      - file.upload-dir=/tmp/uploads-psoft-g1
      - spring.rabbitmq.host=rabbitmq
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8085:8080"
    networks:
      - lms_network

  postgres_query:
    image: postgres:latest
    environment:
      - POSTGRES_DB=query_books
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_query_volume:/var/lib/postgresql
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    ports:
      - "5433:5432"
    networks:
      - lms_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


networks:
  lms_network:
    external: true

volumes:
  postgres_query_volume:
    driver: local